services:
  bloom:
    container_name: bloom
    image: bloom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8201:8081"
    volumes:
      - ./passwords:/usr/src/app/passwords:ro
